resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
images:
  - name: beming/stock-simulator-back
    newTag: c40630b9dfe2a0b864c96dcb8e40674e2393b418
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
