resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
images:
  - name: beming/stock-simulator-back
    newTag: 4e16840427eccde99189cc608c69447a67cc3998
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
