resources:
  - frontend-deploy.yaml
  - frontend-svc.yaml
  - namespace-frontend.yaml
images:
  - name: beming/stock-simulator-front
    newTag: e3b8e2db7fc5b9a13280e40bc2c572b783343953
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
